import { Factory } from 'ember-cli-mirage';

export default Factory.extend({

  name(i) {
    let values = [ 'Default', 'My Company' ];

    return values[i % values.length];
  },

  user(i) {
    let values = [ 'conanci', 'mycompany' ];

    return values[i % values.length];
  },

  conan_verify_ssl() {
    return true;
  },

  conan_remote() {
    return 'http://test-conan-server:9300';
  },

  conan_user() {
    return 'agent';
  },

  conan_password() {
    return 'demo';
  },

  public_ssh_key() {
    return `
      c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFDZHNqZmRzYWpmaWRzb2ZqZHNpZnZj
      eHZjeEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUNkc2pmZHNhamZpZHNvZmpkc2lmdmN4dmN4
      QUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQ2RzamZkc2FqZmlkc29mamRzaWZ2Y3h2Y3g=
      `;
  },

  known_hosts() {
    return `
      Z2l0aHViLmNvbSwxNDAuODIuMTIxLjQgc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBQkl3QUFBUUVBcTJBN
      2hSR21kbm05dFVEYk85SURTd0JLNlRiUWErUFhZUENQeTZyYlRyVHR3N1BIa2NjS3JwcDB5VmhwNUhkRUljS3
      I2cExsVkRCZk9MWDlRVXN5Q09WMHd6ZmpJSk5sR0VZc2RsTEppekhoYm4ybVVqdlNBSFFxWkVUWVA4MWVGekx
      RTm5QSHQ0RVZWVWg3VmZERVNVODRLZXptRDVRbFdwWExtdlUzMS95TWYrU2U4eGhIVHZLU0NaSUZJbVd3b0c2
      bWJVb1dmOW56cElvYVNqQit3ZXFxVVVtcGFhYXNYVmFsNzJKK1VYMkIrMlJQVzNSY1QwZU96UWdxbEpMM1JLc
      lRKdmRzakUzSkVBdkdxM2xHSFNaWHkyOEczc2t1YTJTbVZpL3c0eUNFNmdiT0RxblRXbGc3K3dDNjA0eWRHWE
      E4VkppUzVhcDQzSlhpVUZGQWFRPT0K
      `;
  },

  settings() {
    return `
      CiMgT25seSBmb3IgY3Jvc3MgYnVpbGRpbmcsICdvc19idWlsZC9hcmNoX2J1aWxkJyBpcyB0aGUg
      c3lzdGVtIHRoYXQgcnVucyBDb25hbgpvc19idWlsZDogW1dpbmRvd3MsIFdpbmRvd3NTdG9yZSwg
      TGludXgsIE1hY29zLCBGcmVlQlNELCBTdW5PUywgQUlYXQphcmNoX2J1aWxkOiBbeDg2LCB4ODZf
      NjQsIHBwYzMyYmUsIHBwYzMyLCBwcGM2NGxlLCBwcGM2NCwgYXJtdjVlbCwgYXJtdjVoZiwgYXJt
      djYsIGFybXY3LCBhcm12N2hmLCBhcm12N3MsIGFybXY3aywgYXJtdjgsIGFybXY4XzMyLCBhcm12
      OC4zLCBzcGFyYywgc3BhcmN2OSwgbWlwcywgbWlwczY0LCBhdnIsIHMzOTAsIHMzOTB4LCBzaDRs
      ZV0KCiMgT25seSBmb3IgYnVpbGRpbmcgY3Jvc3MgY29tcGlsYXRpb24gdG9vbHMsICdvc190YXJn
      ZXQvYXJjaF90YXJnZXQnIGlzIHRoZSBzeXN0ZW0gZm9yCiMgd2hpY2ggdGhlIHRvb2xzIGdlbmVy
      YXRlIGNvZGUKb3NfdGFyZ2V0OiBbV2luZG93cywgTGludXgsIE1hY29zLCBBbmRyb2lkLCBpT1Ms
      IHdhdGNoT1MsIHR2T1MsIEZyZWVCU0QsIFN1bk9TLCBBSVgsIEFyZHVpbm8sIE5ldXRyaW5vXQph
      cmNoX3RhcmdldDogW3g4NiwgeDg2XzY0LCBwcGMzMmJlLCBwcGMzMiwgcHBjNjRsZSwgcHBjNjQs
      IGFybXY1ZWwsIGFybXY1aGYsIGFybXY2LCBhcm12NywgYXJtdjdoZiwgYXJtdjdzLCBhcm12N2ss
      IGFybXY4LCBhcm12OF8zMiwgYXJtdjguMywgc3BhcmMsIHNwYXJjdjksIG1pcHMsIG1pcHM2NCwg
      YXZyLCBzMzkwLCBzMzkweCwgYXNtLmpzLCB3YXNtLCBzaDRsZV0KCiMgUmVzdCBvZiB0aGUgc2V0
      dGluZ3MgYXJlICJob3N0IiBzZXR0aW5nczoKIyAtIEZvciBuYXRpdmUgYnVpbGRpbmcvY3Jvc3Mg
      YnVpbGRpbmc6IFdoZXJlIHRoZSBsaWJyYXJ5L3Byb2dyYW0gd2lsbCBydW4uCiMgLSBGb3IgYnVp
      bGRpbmcgY3Jvc3MgY29tcGlsYXRpb24gdG9vbHM6IFdoZXJlIHRoZSBjcm9zcyBjb21waWxlciB3
      aWxsIHJ1bi4Kb3M6CiAgICBXaW5kb3dzOgogICAgICAgIHN1YnN5c3RlbTogW05vbmUsIGN5Z3dp
      biwgbXN5cywgbXN5czIsIHdzbF0KICAgIFdpbmRvd3NTdG9yZToKICAgICAgICB2ZXJzaW9uOiBb
      IjguMSIsICIxMC4wIl0KICAgIFdpbmRvd3NDRToKICAgICAgICBwbGF0Zm9ybTogQU5ZCiAgICAg
      ICAgdmVyc2lvbjogWyI1LjAiLCAiNi4wIiwgIjcuMCIsICI4LjAiXQogICAgTGludXg6CiAgICBN
      YWNvczoKICAgICAgICB2ZXJzaW9uOiBbTm9uZSwgIjEwLjYiLCAiMTAuNyIsICIxMC44IiwgIjEw
      LjkiLCAiMTAuMTAiLCAiMTAuMTEiLCAiMTAuMTIiLCAiMTAuMTMiLCAiMTAuMTQiLCAiMTAuMTUi
      LCAiMTEuMCJdCiAgICBBbmRyb2lkOgogICAgICAgIGFwaV9sZXZlbDogQU5ZCiAgICBpT1M6CiAg
      ICAgICAgdmVyc2lvbjogWyI3LjAiLCAiNy4xIiwgIjguMCIsICI4LjEiLCAiOC4yIiwgIjguMyIs
      ICI5LjAiLCAiOS4xIiwgIjkuMiIsICI5LjMiLCAiMTAuMCIsICIxMC4xIiwgIjEwLjIiLCAiMTAu
      MyIsICIxMS4wIiwgIjExLjEiLCAiMTEuMiIsICIxMS4zIiwgIjExLjQiLCAiMTIuMCIsICIxMi4x
      IiwgIjEyLjIiLCAiMTIuMyIsICIxMi40IiwgIjEzLjAiLCAiMTMuMSIsICIxMy4yIiwgIjEzLjMi
      LCAiMTMuNCIsICIxMy41IiwgIjEzLjYiXQogICAgd2F0Y2hPUzoKICAgICAgICB2ZXJzaW9uOiBb
      IjQuMCIsICI0LjEiLCAiNC4yIiwgIjQuMyIsICI1LjAiLCAiNS4xIiwgIjUuMiIsICI1LjMiLCAi
      Ni4wIiwgIjYuMSJdCiAgICB0dk9TOgogICAgICAgIHZlcnNpb246IFsiMTEuMCIsICIxMS4xIiwg
      IjExLjIiLCAiMTEuMyIsICIxMS40IiwgIjEyLjAiLCAiMTIuMSIsICIxMi4yIiwgIjEyLjMiLCAi
      MTIuNCIsICIxMy4wIl0KICAgIEZyZWVCU0Q6CiAgICBTdW5PUzoKICAgIEFJWDoKICAgIEFyZHVp
      bm86CiAgICAgICAgYm9hcmQ6IEFOWQogICAgRW1zY3JpcHRlbjoKICAgIE5ldXRyaW5vOgogICAg
      ICAgIHZlcnNpb246IFsiNi40IiwgIjYuNSIsICI2LjYiLCAiNy4wIiwgIjcuMSJdCmFyY2g6IFt4
      ODYsIHg4Nl82NCwgcHBjMzJiZSwgcHBjMzIsIHBwYzY0bGUsIHBwYzY0LCBhcm12NCwgYXJtdjRp
      LCBhcm12NWVsLCBhcm12NWhmLCBhcm12NiwgYXJtdjcsIGFybXY3aGYsIGFybXY3cywgYXJtdjdr
      LCBhcm12OCwgYXJtdjhfMzIsIGFybXY4LjMsIHNwYXJjLCBzcGFyY3Y5LCBtaXBzLCBtaXBzNjQs
      IGF2ciwgczM5MCwgczM5MHgsIGFzbS5qcywgd2FzbSwgc2g0bGVdCmNvbXBpbGVyOgogICAgc3Vu
      LWNjOgogICAgICAgIHZlcnNpb246IFsiNS4xMCIsICI1LjExIiwgIjUuMTIiLCAiNS4xMyIsICI1
      LjE0IiwgIjUuMTUiXQogICAgICAgIHRocmVhZHM6IFtOb25lLCBwb3NpeF0KICAgICAgICBsaWJj
      eHg6IFtsaWJDc3RkLCBsaWJzdGRjeHgsIGxpYnN0bHBvcnQsIGxpYnN0ZGMrK10KICAgIGdjYzog
      JmdjYwogICAgICAgIHZlcnNpb246IFsiNC4xIiwgIjQuNCIsICI0LjUiLCAiNC42IiwgIjQuNyIs
      ICI0LjgiLCAiNC45IiwKICAgICAgICAgICAgICAgICAgIjUiLCAiNS4xIiwgIjUuMiIsICI1LjMi
      LCAiNS40IiwgIjUuNSIsCiAgICAgICAgICAgICAgICAgICI2IiwgIjYuMSIsICI2LjIiLCAiNi4z
      IiwgIjYuNCIsICI2LjUiLAogICAgICAgICAgICAgICAgICAiNyIsICI3LjEiLCAiNy4yIiwgIjcu
      MyIsICI3LjQiLCAiNy41IiwKICAgICAgICAgICAgICAgICAgIjgiLCAiOC4xIiwgIjguMiIsICI4
      LjMiLCAiOC40IiwKICAgICAgICAgICAgICAgICAgIjkiLCAiOS4xIiwgIjkuMiIsICI5LjMiLAog
      ICAgICAgICAgICAgICAgICAiMTAiLCAiMTAuMSJdCiAgICAgICAgbGliY3h4OiBbbGlic3RkYysr
      LCBsaWJzdGRjKysxMV0KICAgICAgICB0aHJlYWRzOiBbTm9uZSwgcG9zaXgsIHdpbjMyXSAjICBX
      aW5kb3dzIE1pbkdXCiAgICAgICAgZXhjZXB0aW9uOiBbTm9uZSwgZHdhcmYyLCBzamxqLCBzZWhd
      ICMgV2luZG93cyBNaW5HVwogICAgICAgIGNwcHN0ZDogW05vbmUsIDk4LCBnbnU5OCwgMTEsIGdu
      dTExLCAxNCwgZ251MTQsIDE3LCBnbnUxNywgMjAsIGdudTIwXQogICAgVmlzdWFsIFN0dWRpbzog
      JnZpc3VhbF9zdHVkaW8KICAgICAgICBydW50aW1lOiBbTUQsIE1ULCBNVGQsIE1EZF0KICAgICAg
      ICB2ZXJzaW9uOiBbIjgiLCAiOSIsICIxMCIsICIxMSIsICIxMiIsICIxNCIsICIxNSIsICIxNiJd
      CiAgICAgICAgdG9vbHNldDogW05vbmUsIHY5MCwgdjEwMCwgdjExMCwgdjExMF94cCwgdjEyMCwg
      djEyMF94cCwKICAgICAgICAgICAgICAgICAgdjE0MCwgdjE0MF94cCwgdjE0MF9jbGFuZ19jMiwg
      TExWTS12czIwMTIsIExMVk0tdnMyMDEyX3hwLAogICAgICAgICAgICAgICAgICBMTFZNLXZzMjAx
      MywgTExWTS12czIwMTNfeHAsIExMVk0tdnMyMDE0LCBMTFZNLXZzMjAxNF94cCwKICAgICAgICAg
      ICAgICAgICAgTExWTS12czIwMTcsIExMVk0tdnMyMDE3X3hwLCB2MTQxLCB2MTQxX3hwLCB2MTQx
      X2NsYW5nX2MyLCB2MTQyLAogICAgICAgICAgICAgICAgICBsbHZtLCBDbGFuZ0NMXQogICAgICAg
      IGNwcHN0ZDogW05vbmUsIDE0LCAxNywgMjBdCiAgICBjbGFuZzoKICAgICAgICB2ZXJzaW9uOiBb
      IjMuMyIsICIzLjQiLCAiMy41IiwgIjMuNiIsICIzLjciLCAiMy44IiwgIjMuOSIsICI0LjAiLAog
      ICAgICAgICAgICAgICAgICAiNS4wIiwgIjYuMCIsICI3LjAiLCAiNy4xIiwKICAgICAgICAgICAg
      ICAgICAgIjgiLCAiOSIsICIxMCJdCiAgICAgICAgbGliY3h4OiBbTm9uZSwgbGlic3RkYysrLCBs
      aWJzdGRjKysxMSwgbGliYysrLCBjKytfc2hhcmVkLCBjKytfc3RhdGljXQogICAgICAgIGNwcHN0
      ZDogW05vbmUsIDk4LCBnbnU5OCwgMTEsIGdudTExLCAxNCwgZ251MTQsIDE3LCBnbnUxNywgMjAs
      IGdudTIwXQogICAgICAgIHJ1bnRpbWU6IFtOb25lLCBNRCwgTVQsIE1UZCwgTURkXQogICAgYXBw
      bGUtY2xhbmc6ICZhcHBsZV9jbGFuZwogICAgICAgIHZlcnNpb246IFsiNS4wIiwgIjUuMSIsICI2
      LjAiLCAiNi4xIiwgIjcuMCIsICI3LjMiLCAiOC4wIiwgIjguMSIsICI5LjAiLCAiOS4xIiwgIjEw
      LjAiLCAiMTEuMCIsICIxMi4wIl0KICAgICAgICBsaWJjeHg6IFtsaWJzdGRjKyssIGxpYmMrK10K
      ICAgICAgICBjcHBzdGQ6IFtOb25lLCA5OCwgZ251OTgsIDExLCBnbnUxMSwgMTQsIGdudTE0LCAx
      NywgZ251MTcsIDIwLCBnbnUyMF0KICAgIGludGVsOgogICAgICAgIHZlcnNpb246IFsiMTEiLCAi
      MTIiLCAiMTMiLCAiMTQiLCAiMTUiLCAiMTYiLCAiMTciLCAiMTgiLCAiMTkiLCAiMTkuMSJdCiAg
      ICAgICAgYmFzZToKICAgICAgICAgICAgZ2NjOgogICAgICAgICAgICAgICAgPDw6ICpnY2MKICAg
      ICAgICAgICAgICAgIHRocmVhZHM6IFtOb25lXQogICAgICAgICAgICAgICAgZXhjZXB0aW9uOiBb
      Tm9uZV0KICAgICAgICAgICAgVmlzdWFsIFN0dWRpbzoKICAgICAgICAgICAgICAgIDw8OiAqdmlz
      dWFsX3N0dWRpbwogICAgICAgICAgICBhcHBsZS1jbGFuZzoKICAgICAgICAgICAgICAgIDw8OiAq
      YXBwbGVfY2xhbmcKICAgIHFjYzoKICAgICAgICB2ZXJzaW9uOiBbIjQuNCIsICI1LjQiLCAiOC4z
      Il0KICAgICAgICBsaWJjeHg6IFtjeHgsIGdwcCwgY3BwLCBjcHAtbmUsIGFjY3AsIGFjcHAtbmUs
      IGVjcHAsIGVjcHAtbmVdCiAgICAgICAgY3Bwc3RkOiBbTm9uZSwgOTgsIGdudTk4LCAxMSwgZ251
      MTEsIDE0LCBnbnUxNCwgMTcsIGdudTE3XQoKYnVpbGRfdHlwZTogW05vbmUsIERlYnVnLCBSZWxl
      YXNlLCBSZWxXaXRoRGViSW5mbywgTWluU2l6ZVJlbF0KCgpjcHBzdGQ6IFtOb25lLCA5OCwgZ251
      OTgsIDExLCBnbnUxMSwgMTQsIGdudTE0LCAxNywgZ251MTcsIDIwLCBnbnUyMF0gICMgRGVwcmVj
      YXRlZCwgdXNlIGNvbXBpbGVyLmNwcHN0ZAo=
      `;
  }

});
